#!/bin/sh

set -e

case "$1" in
   configure)
        systemctl stop systemd-resolved.service || true
        systemctl mask systemd-resolved.service

	if [ -L /etc/resolv.conf ]; then
		rm /etc/resolv.conf
		touch /etc/resolv.conf
	fi

	systemctl restart network-manager || true
   ;;

   abort-upgrade|abort-remove|abort-deconfigure)
   ;;

   *)
       exit 1
   ;;
esac

#DEBHELPER#

exit 0

