#!/bin/sh

set -e

case "$1" in
   configure)
        systemctl stop systemd-resolved.service || true
        systemctl mask systemd-resolved.service
        [ ! -L /etc/resolv.conf ] || rm /etc/resolv.conf
	systemctl restart network-manager || true
   ;;

   abort-upgrade|abort-remove|abort-deconfigure)
   ;;

   *)
       exit 1
   ;;
esac

#DEBHELPER#

exit 0

